version: '2'
services:
  miniconda:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ${local_volum}:/opt/d2l-en
    stdin_open: true # docker run -i
    tty: true        # docker run -t